<?php

class MethodNameStartsWithGetIs
{
  public function isBar()
  {
  }

  private function getBar()
  {
  }

  protected function getIsStuff()
  {
  }

  public function getIsBars()
  {
  }

  public function getIsolation()
  {
  }

  public function getIISServer()
  {
  }

  public function getIsoFrom()
  {
  }

  public
  function
  getisIets1()
  {
  }

  public function getisIets2()
  {
  }

  public function 	getisIetsTab2()
  {
  }

  public
  function
    getisIets3()
  {
  }

  public
  function
      getisIets4()
  {
  }

  public function getislande()
  {
  }

  public function get()
  {

  }

  public function get3something()
  {

  }

  public function getIs3()
  {

  }

  public function getIs34()
  {

  }

  public function getIs2late()
  {

  }

  public
  function /*
  sadasdasdd */ getIsoFrom4()
  {
  }

  public
  function //asd asdasd
  # asdasdasd
  getIsoFrom2()
  {
  }
}
